#!/usr/bin/env bash
# This script groups visitors by IP and HTTP code and counts occurrences

awk '{count[$1" "$9]++} END {for (key in count) print count[key], key}' apache-access.log | sort -rn | awk '{$1=$1; print}'
