#!/usr/bin/env bash
# Loops from 1 to 20, prints number, and displays bad luck messages for specific iterations
hour=0 
while [ "$hour" -le 59]; do
    minute=0
    while [ "$minute" -le 59]; do
        minute=$((minute + 1))
    done
    hour=$((hour + 1))
done | head -n 70
