#!/usr/bin/env bash
# Displays hours 0-12 and minutes 1-59, first 70 lines, safely with head

hour=0
while [ "$hour" -le 12 ]; do
    minute=1
    while [ "$minute" -le 59 ]; do
        echo "$hour:$minute" || break   # если pipe закрыт, прекращаем цикл
        minute=$((minute + 1))
    done
    hour=$((hour + 1))
done | head -n 70
