#!/usr/bin/env bash
# a Bash script that displays the PID, along with the process name, of processes whose name contain the word bash.
for pid in /proc/[0-9]*; do
    if [ -f "$pid/comm" ]; then
        name=$(cat "$pid/comm")
        if [[ $name == *bash* ]]; then
            echo "$(basename "$pid") $name"
        fi
    fi
done

