#!/usr/bin/env bash
# Script that prints "To infinity and beyond" indefinitely
handle_sigterm() {
    echo "I am invincible!!!"
}

trap 'handle_sigterm' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done

